type: object
description: |
  JSON File Name. 
  It is the initial value of transform information and GPSTIME of the point cloud map for registration. 
  Even when registering multiple mesh files, there is only one JSON file. When registering mesh data with different JSON information, it is necessary to register them separately.

  ※The explanation below config is the explanation of json contents. and The request samples on the right side are only samples of JSON files.
properties:
  transformCRS:
    description: |
      Coordinate system of the posted point cloud file.

      The format is a URI indicating the EPSG code from `opengis.net`.
      That is, a string prefixed with `https://www.opengis.net/def/crs/EPSG/`.

      For example:
      * WGS84: <https://www.opengis.net/def/crs/EPSG/0/4326>
      * JGD2011 / Japan Plane Rectangular CS IX: <https://www.opengis.net/def/crs/EPSG/0/6677>

      The default value is determined from one of the following ranges, based on the value of `origin` in `transform`.
      * <http://www.opengis.net/def/crs/EPSG/0/32601> to <http://www.opengis.net/def/crs/EPSG/0/32660>
      * <http://www.opengis.net/def/crs/EPSG/0/32701> to <http://www.opengis.net/def/crs/EPSG/0/32760>

      If transform is specified, the coordinate system in transformCRS means the coordinates of each point in the point cloud file which is transformed based on origin, euler and scale in transform.
    type: string
    example: http://www.opengis.net/def/crs/EPSG/0/4326
  transform:
    $ref: Transform.yml
  gpsTime:
    description: >
      This timestamp is used for a point cloud which has no explicit GPS timestamp 
      of the data creation/acquisition.
    type: string
    format: date-time
    example: '2017-08-17T08:05:32Z'
